#!/usr/bin/env bash

PRODUCTNAME="yayfzf"
VERSION="0.1.4"
LICENSE="GNU General Public License, version 3"
WEBSITE="https://github.com/ConnerWill/yayfzf"
AUTHOR="ConnerWill"
DATE="2022-07-31"

# _keybinding_file="../config/KEYBINDINGS.conf"
# [[ -e "$_keybinding_file" ]] && source "$_keybinding_file" || KEYBINDINGS=""


function _version() {
	cat <<EOS
========================================================
    NAME    :    ${PRODUCTNAME}
    VERSION :    v${VERSION}
    DATE    :    ${DATE}
    LICENCE :    ${LICENSE}
    AUTHOR  :    ${AUTHOR}
    WEBSITE :    ${WEBSITE}/${AUTHOR}
========================================================
EOS
}

function _help() {
	cat <<EOS
"
========================================================"

    NAME
        yayfzf

    DESCRIPTION
        search and install packages from the AUR with fzf

    USAGE
        yayfzf    KEYWORDS...
        yayfzf    -h|--help
        yayfzf    -V|--version

    KEYBINDINGS
$KEYBINDINGS

========================================================
"
EOS
}

_yayfzf_keys() {
  cat <<EOF
Keybindings:
	Alt+d           Install Package(s)
	Tab 						Toggle Selection
	Ctl+Tab					Deselect
	PageUp 		      Page up
	PageDown 		    Page Down
	Home						Top
	End 						Bottom
	Ctrl+/          Change Window Layout
	? 	            Show keybindings.
	Ctl+h|F1	      Help
	Esc|Ctl+q       Exit
EOF
}
