.\" Manpage for yayfzf
.TH yayfzf 1 "2026-01-06" "1.0.6" "yayfzf manual"
.SH NAME
yayfzf \- interactively search, install, and remove AUR packages using fzf
.SH SYNOPSIS
.B yayfzf
[\fIOPTIONS\fR] [\fISEARCH QUERY\fR]
.SH DESCRIPTION
Search, install, and remove packages from the AUR interactively with fzf.
.SH OPTIONS
.TP
\-h
Show the help menu
.TP
\-\-help
Show the extended help menu
.TP
\-k, \-\-keybindings
List keybindings for yayfzf
.TP
\-V, \-\-version
Show version of yayfzf
.SH EXAMPLES
$ yayfzf
Run yayfzf with no search query
$ yayfzf fzf
Search for 'fzf' with yayfzf
$ yayfzf
Show the help menu
.SH KEYBINDINGS
See the tool for a full list of keybindings.
.SH SEE ALSO
.BR fzf (1)
.BR yay (1)
.SH AUTHOR
Conner Will <conner.will@connerwill.com>
