.\" Manpage for yayfzf
.TH yayfzf 1 "2026-01-06" "2.0.13" "yayfzf manual"

.SH NAME
yayfzf \- interactively search, install, and remove AUR packages using fzf


.SH SYNOPSIS
.B yayfzf [\fIOPTIONS\fR] [\fISEARCH QUERY\fR]


.SH DESCRIPTION
Search, install, and remove packages from the AUR interactively with fzf.


.SH OPTIONS
.TP
.B \-k, \-\-keybindings
Show the list of available keybindings and exit.

.TP
.B \-i, \-\-init-config
Install an example configuration file to the XDG config directory and exit.

.TP
.B \-s, \-\-show-config
Print the example configuration file to stdout and exit.

.TP
.B \-v, \-\-verbose
Show verbose output

.TP
.B \-h
Show the short help text and exit.

.TP
.B \-\-help
Show full help, including keybindings and config file locations, and exit.

.TP
.B \-\-help\-man
Show manpage help and exit.

.TP
.B \-V, \-\-version
Show the yayfzf version and exit.

.SH EXAMPLES
.TP
.B $ yayfzf
Run yayfzf with no search query

.TP
.B $ yayfzf fzf
Search for 'fzf' with yayfzf

.TP
.B $ yayfzf \-h
Show the help menu


.SH KEYBINDINGS

.TP
.B ↑
Move up

.TP
.B ↓
Move down

.TP
.B PGUP
Move up one page

.TP
.B PGDN
Move down one page

.TP
.B HOME
Move to first

.TP
.B END
Move to last

.TP
.B TAB
Select item.

.TP
.B Shift\-TAB
Unselect item.

.TP
.B Ctrl\-a
Select all items.

.TP
.B Ctrl\-d
Deselect all selected items.

.TP
.B ENTER
Perform action on the current selection.

.TP
.B Ctrl\-i
Install selected packages

.TP
.B Ctrl\-r
Uninstall package

.TP
.B Ctrl\-u
Update all packages

.TP
.B Ctrl\-l
Clear the current search query and screen.

.TP
.B Ctrl\-Backspace
Clear the current search query.

.TP
.B Ctrl\-/
Cycle fzf layout and preview window position.

.TP
.B Ctrl\-v
Toggle the preview window.

.TP
.B ?
Show keybindings.

.TP
.B Ctrl\-c
Exit yayfzf.

.TP
.B Ctrl\-w
Exit yayfzf.

.TP
.B ESC
Exit yayfzf.


.SH ENVIRONMENT
.TP
.B YAYFZF_PREVIEW_WINDOW
Controls the layout and size of the fzf preview window.

The value is passed directly to fzf’s
.BR --preview-window
option.

Default:
.RS
.B bottom,43%,border-double
.RE

.TP
.B NO_COLOR
Disable all ANSI color output.

When set, yayfzf disables:
.RS
.IP \(bu 2
fzf color themes
.IP \(bu 2
ANSI color output in messages

.PP
This follows the
.B NO_COLOR
convention used by many CLI tools.
.RE


.SH SEE ALSO
.BR fzf (1)
.BR yay (1)
.BR rclonefzf (1)


.SH AUTHOR
Conner Will <conner.will@connerwill.com>
